name: Labels

labels:
  - name: bug
    color: f98181
    description: Something isn't working

  - name: feature
    color: 009688
    description: New feature or request

  - name: enhancement
    color: 79b8ff
    description: Improvement to existing feature

  - name: documentation
    color: 7cb342
    description: Improvements or additions to documentation

  - name: help wanted
    color: ffffff
    description: Need some help with this issue

  - name: good first issue
    color: b39ddb
    description: Good for newcomers

  - name: duplicate
    color: ffcc80
    description: This issue or pull request already exists

  - name: invalid
    color: e57373
    description: This doesn't seem right

  - name: wontfix
    color: 000000
    description: This will not be worked on
