import { cn } from '@/lib/utils'
// import { base, heading } from '@/constants/fonts'
// import { cn } from '@/lib'
import '@/styles/globals.css'
import { generateMetadata } from '@/utils'
import { ThemeProvider } from 'next-themes'
import { Toaster } from 'sonner'
import { Geist_Mono } from 'next/font/google'
// import { ClerkProvider } from '@clerk/nextjs'

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata = generateMetadata()

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          `${geistMono.variable} dark text-foreground min-h-screen overflow-x-hidden bg-[#000000] font-mono antialiased`,
        )}
      >
        {/* <ClerkProvider> */}
        <Toaster richColors theme="dark" position="bottom-center" />
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
        {/* </ClerkProvider> */}
      </body>
    </html>
  )
}

// import type { Metadata } from 'next'
// import { Geist, Geist_Mono } from 'next/font/google'
// import './globals.css'

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// })

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode
// }>) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>{children}</body>
//     </html>
//   )
// }
